// Mock data for local development when Appwrite is not configured

export const mockCategories: any[] = [
    { id: '1', name: 'Cardiovascular', nameAr: 'القلب والأوعية الدموية', slug: 'cardiovascular', type: 'human', icon: '❤️', description: 'Heart and blood vessel medications' },
    { id: '2', name: 'Anti-Infectives', nameAr: 'مضادات العدوى', slug: 'anti-infectives', type: 'human', icon: '🦠', description: 'Antibiotics and antimicrobials' },
    { id: '3', name: 'Companion Animals', nameAr: 'الحيوانات الأليفة', slug: 'companion-animals', type: 'veterinary', icon: '🐕', description: 'For dogs and cats' },
    { id: '4', name: 'Livestock', nameAr: 'الماشية', slug: 'livestock', type: 'veterinary', icon: '🐄', description: 'For cattle and livestock' },
];

export const mockHumanProducts: any[] = [
    {
        id: '1',
        name: 'Cardio Plus',
        genericName: 'Atenolol',
        strength: '50mg',
        dosageForm: 'Tablets',
        indication: 'Hypertension',
        packSize: '30 tablets',
        registrationNumber: 'HP-2024-001',
        category: 'cardiovascular',
        imageUrl: null,
        price: 150,
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Antibiotic Pro',
        genericName: 'Amoxicillin',
        strength: '500mg',
        dosageForm: 'Capsules',
        indication: 'Bacterial infections',
        packSize: '21 capsules',
        registrationNumber: 'HP-2024-002',
        category: 'anti-infectives',
        imageUrl: null,
        price: 120,
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
];

export const mockVeterinaryProducts: any[] = [
    {
        id: '1',
        name: 'Vet Care Plus',
        genericName: 'Ivermectin',
        strength: '10mg/ml',
        dosageForm: 'Injectable Solution',
        indication: 'Parasitic infections',
        species: 'Dogs, Cats',
        withdrawalPeriod: null,
        packSize: '50ml vial',
        registrationNumber: 'VP-2024-001',
        category: 'companion-animals',
        imageUrl: null,
        price: 200,
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Livestock Shield',
        genericName: 'Oxytetracycline',
        strength: '200mg/ml',
        dosageForm: 'Injectable Solution',
        indication: 'Respiratory infections',
        species: 'Cattle, Sheep',
        withdrawalPeriod: '28 days',
        packSize: '100ml vial',
        registrationNumber: 'VP-2024-002',
        category: 'livestock',
        imageUrl: null,
        price: 350,
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
];

export const mockMediaPosts: any[] = [
    {
        id: '1',
        title: 'New Product Launch',
        titleAr: 'إطلاق منتج جديد',
        content: 'We are excited to announce our new cardiovascular medication line.',
        contentAr: 'يسرنا أن نعلن عن خط الأدوية الجديد للقلب والأوعية الدموية.',
        type: 'news',
        mediaType: 'image',
        mediaUrl: null,
        isActive: true,
        publishDate: new Date().toISOString(),
        $createdAt: new Date().toISOString(),
    },
];

export const mockJobs: any[] = [
    {
        id: '1',
        $id: '1',
        title: 'Senior Pharmacist',
        titleAr: 'صيدلي أول',
        department: 'Quality Assurance',
        location: 'Cairo, Egypt',
        jobType: 'full-time',
        workingHours: '8:00 AM - 4:00 PM',
        description: 'We are looking for a highly qualified senior pharmacist to join our Quality Assurance team. The ideal candidate will have extensive experience in pharmaceutical quality control and regulatory compliance.',
        descriptionAr: 'نبحث عن صيدلي أول مؤهل للانضمام إلى فريق ضمان الجودة. يجب أن يكون لدى المرشح المثالي خبرة واسعة في مراقبة الجودة الدوائية والامتثال التنظيمي.',
        requirements: '• Bachelor degree in Pharmacy\n• 5+ years experience in pharmaceutical industry\n• Strong knowledge of GMP and quality standards\n• Excellent communication skills',
        requirementsAr: '• بكالوريوس في الصيدلة\n• خبرة 5 سنوات أو أكثر في صناعة الأدوية\n• معرفة قوية بمعايير GMP والجودة\n• مهارات تواصل ممتازة',
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        $id: '2',
        title: 'Production Supervisor',
        titleAr: 'مشرف إنتاج',
        department: 'Production',
        location: 'Alexandria, Egypt',
        jobType: 'full-time',
        workingHours: '7:00 AM - 3:00 PM',
        description: 'Seeking an experienced production supervisor to oversee manufacturing operations. Must ensure production targets are met while maintaining quality standards.',
        descriptionAr: 'نبحث عن مشرف إنتاج ذو خبرة للإشراف على عمليات التصنيع. يجب التأكد من تحقيق أهداف الإنتاج مع الحفاظ على معايير الجودة.',
        requirements: '• Degree in Pharmaceutical Sciences or related field\n• 3+ years supervisory experience\n• Knowledge of manufacturing processes\n• Leadership and team management skills',
        requirementsAr: '• شهادة في العلوم الصيدلانية أو مجال ذي صلة\n• خبرة إشرافية 3 سنوات أو أكثر\n• معرفة بعمليات التصنيع\n• مهارات القيادة وإدارة الفريق',
        isActive: true,
        $createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
        id: '3',
        $id: '3',
        title: 'Veterinary Sales Representative',
        titleAr: 'مندوب مبيعات بيطرية',
        department: 'Sales & Marketing',
        location: 'Multiple Locations',
        jobType: 'full-time',
        workingHours: 'Flexible',
        description: 'Join our veterinary division as a sales representative. You will be responsible for promoting our veterinary pharmaceutical products to veterinarians and animal health professionals.',
        descriptionAr: 'انضم إلى قسم البيطرة كمندوب مبيعات. ستكون مسؤولاً عن الترويج لمنتجاتنا الصيدلانية البيطرية للأطباء البيطريين ومتخصصي صحة الحيوان.',
        requirements: '• Bachelor degree in Veterinary Medicine or related field\n• 2+ years sales experience preferred\n• Valid driver\'s license\n• Strong communication and negotiation skills',
        requirementsAr: '• بكالوريوس في الطب البيطري أو مجال ذي صلة\n• خبرة 2 سنوات في المبيعات مفضلة\n• رخصة قيادة سارية\n• مهارات تواصل وتفاوض قوية',
        isActive: true,
        $createdAt: new Date(Date.now() - 172800000).toISOString(),
    },
];

export const mockJobApplications: any[] = [
    {
        id: 'app1',
        $id: 'app1',
        jobId: '1',
        fullName: 'Ahmed Hassan',
        email: 'ahmed.hassan@email.com',
        phone: '+20 100 123 4567',
        coverLetter: 'I am very interested in the Senior Pharmacist position and believe my experience aligns well with the requirements.',
        cvUrl: '/uploads/cvs/ahmed_hassan_cv.pdf',
        status: 'pending',
        $createdAt: new Date().toISOString(),
    },
    {
        id: 'app2',
        $id: 'app2',
        jobId: '1',
        fullName: 'Sara Mohamed',
        email: 'sara.mohamed@email.com',
        phone: '+20 101 234 5678',
        coverLetter: 'With 7 years of experience in pharmaceutical QA, I am confident I can contribute to your team.',
        cvUrl: '/uploads/cvs/sara_mohamed_cv.pdf',
        status: 'reviewed',
        $createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: 'app3',
        $id: 'app3',
        jobId: '2',
        fullName: 'Khaled Ali',
        email: 'khaled.ali@email.com',
        phone: '+20 102 345 6789',
        coverLetter: 'I have extensive experience in production management and would love to join Sobek Pharma.',
        cvUrl: '/uploads/cvs/khaled_ali_cv.pdf',
        status: 'shortlisted',
        $createdAt: new Date(Date.now() - 7200000).toISOString(),
    },
];

export const mockLeadership: any[] = [
    {
        id: '1',
        name: 'Dr. Ahmed Mohamed',
        nameAr: 'د. أحمد محمد',
        position: 'CEO',
        positionAr: 'المدير التنفيذي',
        bio: 'Leading pharmaceutical expert with 20+ years of experience.',
        bioAr: 'خبير صيدلاني رائد مع أكثر من 20 عامًا من الخبرة.',
        imageUrl: null,
        order: 1,
        $createdAt: new Date().toISOString(),
    },
];
