// Mock data for local development when Appwrite is not configured

export const mockCategories: any[] = [
    { id: '1', name: 'Cardiovascular', nameAr: 'القلب والأوعية الدموية', slug: 'cardiovascular', type: 'human', icon: '❤️', description: 'Heart and blood vessel medications' },
    { id: '2', name: 'Anti-Infectives', nameAr: 'مضادات العدوى', slug: 'anti-infectives', type: 'human', icon: '🦠', description: 'Antibiotics and antimicrobials' },
    { id: '3', name: 'Companion Animals', nameAr: 'الحيوانات الأليفة', slug: 'companion-animals', type: 'veterinary', icon: '🐕', description: 'For dogs and cats' },
    { id: '4', name: 'Livestock', nameAr: 'الماشية', slug: 'livestock', type: 'veterinary', icon: '🐄', description: 'For cattle and livestock' },
];

export const mockHumanProducts: any[] = [
    {
        id: '1',
        name: 'Cardio Plus',
        genericName: 'Atenolol',
        strength: '50mg',
        dosageForm: 'Tablets',
        indication: 'Hypertension',
        packSize: '30 tablets',
        registrationNumber: 'HP-2024-001',
        category: 'cardiovascular',
        imageUrl: null,
        price: 150,
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Antibiotic Pro',
        genericName: 'Amoxicillin',
        strength: '500mg',
        dosageForm: 'Capsules',
        indication: 'Bacterial infections',
        packSize: '21 capsules',
        registrationNumber: 'HP-2024-002',
        category: 'anti-infectives',
        imageUrl: null,
        price: 120,
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
];

export const mockVeterinaryProducts: any[] = [
    {
        id: '1',
        name: 'Vet Care Plus',
        genericName: 'Ivermectin',
        strength: '10mg/ml',
        dosageForm: 'Injectable Solution',
        indication: 'Parasitic infections',
        species: 'Dogs, Cats',
        withdrawalPeriod: null,
        packSize: '50ml vial',
        registrationNumber: 'VP-2024-001',
        category: 'companion-animals',
        imageUrl: null,
        price: 200,
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Livestock Shield',
        genericName: 'Oxytetracycline',
        strength: '200mg/ml',
        dosageForm: 'Injectable Solution',
        indication: 'Respiratory infections',
        species: 'Cattle, Sheep',
        withdrawalPeriod: '28 days',
        packSize: '100ml vial',
        registrationNumber: 'VP-2024-002',
        category: 'livestock',
        imageUrl: null,
        price: 350,
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
];

export const mockMediaPosts: any[] = [
    {
        id: '1',
        title: 'New Product Launch',
        titleAr: 'إطلاق منتج جديد',
        content: 'We are excited to announce our new cardiovascular medication line.',
        contentAr: 'يسرنا أن نعلن عن خط الأدوية الجديد للقلب والأوعية الدموية.',
        type: 'news',
        mediaType: 'image',
        mediaUrl: null,
        isActive: true,
        publishDate: new Date().toISOString(),
        $createdAt: new Date().toISOString(),
    },
];

export const mockJobs: any[] = [
    {
        id: '1',
        $id: '1',
        title: 'QA IPC Supervisor',
        titleAr: 'مشرف مراقبة الجودة أثناء الإنتاج',
        department: 'Quality Assurance',
        location: 'Block 251, Industrial Zone A5, 10th of Ramadan City',
        jobType: 'full-time',
        workingHours: 'Full Time',
        description: 'Sobek Egypt is looking to expand its Quality Assurance and is inviting qualified candidates to apply.\n\n• Leads the IPC team to monitor and ensure product quality during all manufacturing and packaging stages.\n• Verify GMP compliance.\n• Supervise IPC staff.\n• Perform and oversee in-process tests.\n• Document activities, review batch records.\n• Report deviations to management.\n• Aware with data integrity implementation.',
        descriptionAr: 'شركة صوبيك مصر تتطلع لتوسيع فريق ضمان الجودة وتدعو المرشحين المؤهلين للتقديم.\n\n• قيادة فريق IPC لمراقبة وضمان جودة المنتج خلال جميع مراحل التصنيع والتعبئة.\n• التحقق من الامتثال لـ GMP.\n• الإشراف على موظفي IPC.\n• إجراء والإشراف على الاختبارات أثناء العملية.\n• توثيق الأنشطة ومراجعة سجلات الدفعات.\n• الإبلاغ عن الانحرافات للإدارة.\n• الوعي بتطبيق سلامة البيانات.',
        requirements: '• 3-5 years of experience in pharmaceutical IPC\n• Strong knowledge of GMP compliance\n• Experience in supervising IPC teams\n• Ability to perform and oversee in-process tests\n• Document management and batch record review skills\n• Understanding of data integrity principles\n\nPlease send your updated CV (mentioning the job title in the subject line) to: hr@sobek.com.eg',
        requirementsAr: '• خبرة من 3-5 سنوات في مراقبة الجودة أثناء الإنتاج الصيدلاني\n• معرفة قوية بالامتثال لـ GMP\n• خبرة في الإشراف على فرق IPC\n• القدرة على إجراء والإشراف على الاختبارات أثناء العملية\n• مهارات إدارة المستندات ومراجعة سجلات الدفعات\n• فهم مبادئ سلامة البيانات\n\nيرجى إرسال سيرتك الذاتية المحدثة (مع ذكر المسمى الوظيفي في عنوان الموضوع) إلى: hr@sobek.com.eg',
        isActive: true,
        $createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        $id: '2',
        title: 'QA Documentation Section Head',
        titleAr: 'رئيس قسم توثيق الجودة',
        department: 'Quality Assurance',
        location: 'Block 251, Industrial Zone A5, 10th of Ramadan City',
        jobType: 'full-time',
        workingHours: 'Full Time',
        description: 'Sobek Egypt is looking to expand its Quality Assurance and is inviting qualified candidates to apply.\n\n• Lead and manage the Documentation Section (QA Documentation).\n• Establish, implement, and maintain document control systems (SOPs, BMRs, BPRs, formats, records).\n• Ensure compliance with WHO GMP, EDA, EU GMP, and ALCOA+ data integrity principles.\n• Review, approve, issue, archive, and retrieve controlled documents.\n• Ensure timely preparation and issuance of Batch Manufacturing Records and Batch Packaging Records.\n• Monitor document revisions, change control, and version control.\n• Ensure proper archival, retention, and retrieval of GMP documents.\n• Train staff on GMP documentation practices and data integrity.\n• Lead continuous improvement of documentation processes.',
        descriptionAr: 'شركة صوبيك مصر تتطلع لتوسيع فريق ضمان الجودة وتدعو المرشحين المؤهلين للتقديم.\n\n• قيادة وإدارة قسم التوثيق (توثيق ضمان الجودة).\n• إنشاء وتنفيذ وصيانة أنظمة التحكم في المستندات (SOPs, BMRs, BPRs, النماذج، السجلات).\n• ضمان الامتثال لمعايير WHO GMP و EDA و EU GMP ومبادئ ALCOA+ لسلامة البيانات.\n• مراجعة والموافقة على وإصدار وأرشفة واسترجاع المستندات المتحكم بها.\n• ضمان التحضير والإصدار في الوقت المناسب لسجلات تصنيع الدفعات وسجلات تعبئة الدفعات.\n• مراقبة مراجعات المستندات والتحكم في التغييرات والتحكم في الإصدارات.\n• ضمان الأرشفة والاحتفاظ والاسترجاع السليم لمستندات GMP.\n• تدريب الموظفين على ممارسات توثيق GMP وسلامة البيانات.\n• قيادة التحسين المستمر لعمليات التوثيق.',
        requirements: '• 6-8 years of experience in pharmaceutical documentation\n• Strong knowledge of WHO GMP, EDA, EU GMP standards\n• Experience with ALCOA+ data integrity principles\n• Document control systems expertise (SOPs, BMRs, BPRs)\n• Leadership and team management skills\n• Experience in training and development\n• Strong organizational and communication skills\n\nPlease send your updated CV (mentioning the job title in the subject line) to: hr@sobek.com.eg',
        requirementsAr: '• خبرة من 6-8 سنوات في التوثيق الصيدلاني\n• معرفة قوية بمعايير WHO GMP و EDA و EU GMP\n• خبرة في مبادئ ALCOA+ لسلامة البيانات\n• خبرة في أنظمة التحكم في المستندات (SOPs, BMRs, BPRs)\n• مهارات القيادة وإدارة الفريق\n• خبرة في التدريب والتطوير\n• مهارات تنظيمية وتواصل قوية\n\nيرجى إرسال سيرتك الذاتية المحدثة (مع ذكر المسمى الوظيفي في عنوان الموضوع) إلى: hr@sobek.com.eg',
        isActive: true,
        $createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
        id: '3',
        $id: '3',
        title: 'Plant Manager',
        titleAr: 'مدير المصنع',
        department: 'Operations',
        location: 'Block 251, Industrial Zone A5, 10th of Ramadan City',
        jobType: 'full-time',
        workingHours: 'Full Time',
        description: 'Sobek Egypt Pharmaceutical is a fast-growing pharmaceutical company committed to quality, compliance, and operational excellence. We are currently seeking a highly qualified and experienced Plant Manager to lead our manufacturing operations.\n\nKey Responsibilities:\n• Oversee and manage all manufacturing operations to ensure compliance with GMP, GDP, and relevant regulatory requirements.\n• Lead production, engineering, quality, and warehouse teams to achieve operational excellence.\n• Maintain full compliance with Egyptian Drug Authority (EDA) regulations and internal quality systems.\n• Develop and implement production plans aligned with business objectives.\n• Foster a culture of safety, quality, accountability, and performance.',
        descriptionAr: 'شركة صوبيك مصر للأدوية هي شركة أدوية سريعة النمو ملتزمة بالجودة والامتثال والتميز التشغيلي. نحن نبحث حالياً عن مدير مصنع مؤهل وذو خبرة عالية لقيادة عملياتنا التصنيعية.\n\nالمسؤوليات الرئيسية:\n• الإشراف وإدارة جميع عمليات التصنيع لضمان الامتثال لـ GMP و GDP والمتطلبات التنظيمية ذات الصلة.\n• قيادة فرق الإنتاج والهندسة والجودة والمستودعات لتحقيق التميز التشغيلي.\n• الحفاظ على الامتثال الكامل للوائح هيئة الدواء المصرية (EDA) وأنظمة الجودة الداخلية.\n• تطوير وتنفيذ خطط الإنتاج المتوافقة مع أهداف العمل.\n• تعزيز ثقافة السلامة والجودة والمساءلة والأداء.',
        requirements: '• Bachelor\'s degree in Pharmacy\n• Minimum 17 years of experience in pharmaceutical manufacturing\n• At least 2 years of experience in the same role (Plant Manager)\n• Strong background in GMP, quality systems, and pharmaceutical operations\n• Proven leadership, decision-making, and team management skills\n• Experience working with EDA inspections and audits is highly preferred\n• Excellent communication and organizational skills\n\nSend CV to: hr@sobek.com.eg',
        requirementsAr: '• بكالوريوس في الصيدلة\n• خبرة لا تقل عن 17 عاماً في التصنيع الصيدلاني\n• خبرة لا تقل عن سنتين في نفس الدور (مدير مصنع)\n• خلفية قوية في GMP وأنظمة الجودة والعمليات الصيدلانية\n• مهارات قيادة واتخاذ قرار وإدارة فريق مثبتة\n• خبرة في التعامل مع عمليات تفتيش ومراجعة هيئة الدواء المصرية مفضلة للغاية\n• مهارات تواصل وتنظيم ممتازة\n\nأرسل السيرة الذاتية إلى: hr@sobek.com.eg',
        isActive: true,
        $createdAt: new Date(Date.now() - 172800000).toISOString(),
    },
    {
        id: '4',
        $id: '4',
        title: 'QA IPC Specialist',
        titleAr: 'أخصائي مراقبة الجودة أثناء الإنتاج',
        department: 'Quality Assurance',
        location: 'Block 251, Industrial Zone A5, 10th of Ramadan City',
        jobType: 'full-time',
        workingHours: 'Full Time',
        description: 'Sobek Egypt is looking to expand its Quality Assurance and is inviting qualified candidates to apply.\n\nKey Responsibilities:\nEnsures product quality and GMP compliance during manufacturing by performing IPC sampling, testing, inspections, reviewing batch records, verifying line clearance, and reporting deviations to maintain consistency and regulatory compliance. Aware with data integrity implementation.',
        descriptionAr: 'شركة صوبيك مصر تتطلع لتوسيع فريق ضمان الجودة وتدعو المرشحين المؤهلين للتقديم.\n\nالمسؤوليات الرئيسية:\nيضمن جودة المنتج والامتثال لـ GMP أثناء التصنيع من خلال إجراء عينات IPC والاختبار والتفتيش ومراجعة سجلات الدفعات والتحقق من تطهير الخط والإبلاغ عن الانحرافات للحفاظ على الاتساق والامتثال التنظيمي. الوعي بتطبيق سلامة البيانات.',
        requirements: '• 0-2 years of experience in pharmaceutical quality control\n• Knowledge of GMP compliance requirements\n• Understanding of IPC sampling and testing procedures\n• Ability to review batch records and verify line clearance\n• Attention to detail and reporting skills\n• Understanding of data integrity implementation\n\nPlease send your updated CV (mentioning the job title in the subject line) to: hr@sobek.com.eg',
        requirementsAr: '• خبرة من 0-2 سنة في مراقبة الجودة الصيدلانية\n• معرفة بمتطلبات الامتثال لـ GMP\n• فهم إجراءات أخذ العينات والاختبار أثناء العملية\n• القدرة على مراجعة سجلات الدفعات والتحقق من تطهير الخط\n• الاهتمام بالتفاصيل ومهارات إعداد التقارير\n• فهم تطبيق سلامة البيانات\n\nيرجى إرسال سيرتك الذاتية المحدثة (مع ذكر المسمى الوظيفي في عنوان الموضوع) إلى: hr@sobek.com.eg',
        isActive: true,
        $createdAt: new Date(Date.now() - 259200000).toISOString(),
    },
];

export const mockJobApplications: any[] = [
    {
        id: 'app1',
        $id: 'app1',
        jobId: '1',
        fullName: 'Ahmed Hassan',
        email: 'ahmed.hassan@email.com',
        phone: '+20 100 123 4567',
        coverLetter: 'I am very interested in the Senior Pharmacist position and believe my experience aligns well with the requirements.',
        cvUrl: '/uploads/cvs/ahmed_hassan_cv.pdf',
        status: 'pending',
        $createdAt: new Date().toISOString(),
    },
    {
        id: 'app2',
        $id: 'app2',
        jobId: '1',
        fullName: 'Sara Mohamed',
        email: 'sara.mohamed@email.com',
        phone: '+20 101 234 5678',
        coverLetter: 'With 7 years of experience in pharmaceutical QA, I am confident I can contribute to your team.',
        cvUrl: '/uploads/cvs/sara_mohamed_cv.pdf',
        status: 'reviewed',
        $createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: 'app3',
        $id: 'app3',
        jobId: '2',
        fullName: 'Khaled Ali',
        email: 'khaled.ali@email.com',
        phone: '+20 102 345 6789',
        coverLetter: 'I have extensive experience in production management and would love to join Sobek Pharma.',
        cvUrl: '/uploads/cvs/khaled_ali_cv.pdf',
        status: 'shortlisted',
        $createdAt: new Date(Date.now() - 7200000).toISOString(),
    },
];

export const mockLeadership: any[] = [
    {
        id: '1',
        name: 'Dr. Ahmed Mohamed',
        nameAr: 'د. أحمد محمد',
        position: 'CEO',
        positionAr: 'المدير التنفيذي',
        bio: 'Leading pharmaceutical expert with 20+ years of experience.',
        bioAr: 'خبير صيدلاني رائد مع أكثر من 20 عامًا من الخبرة.',
        imageUrl: null,
        order: 1,
        $createdAt: new Date().toISOString(),
    },
];
